name: C/C++ CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate required configuration files (CMake)
      run: cmake .
    - name: Build (CMake)
      run: cmake --build .
